@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Oct 30 21:56:54 +0800 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim mul_test_behav -key {Behavioral:sim_1:Functional:mul_test} -tclbatch mul_test.tcl -view C:/Users/Karloz/Desktop/exp/mul_test_behav.wcfg -log simulate.log"
call xsim  mul_test_behav -key {Behavioral:sim_1:Functional:mul_test} -tclbatch mul_test.tcl -view C:/Users/Karloz/Desktop/exp/mul_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
